---
- name: Gnome Desktop Setup for Ubuntu
  hosts: all
  gather_facts: false
  become: yes
##############################################################
#
  vars:
    nfs_server_path: "192.168.122.1:/mnt/sda3/common"  # NFSサーバーのIPとパス
    mount_point: "/mnt/common"
#
  tasks:
    - name: Include parameter from common.yaml
      include_vars:
        file: ./common.yaml
##############################################################
    - name: Install tools
      ansible.builtin.apt:
        name:
          - ufw			# for firewall setting
          - net-tools		# for ifconfig command
          - curl		# for install any application
          - tcpdump		# for analyze tcp stream
          - auditd		# for check audit log
          - nfs-common		# for nfs mount
          - expect		# for automatic setup
          - net-tools		# for ip address check
        state: present
##############################################################
    - name: Install gedit
      ansible.builtin.apt:
        name: gedit
        state: present
##############################################################
# タイムゾーンを日本（Asia/Tokyo）に設定
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Asia/Tokyo
##############################################################
    - name: Install Desktop Icons NG
      apt:
        name: gnome-shell-extension-desktop-icons-ng
        state: present
# --------------------------------------------------------------------------
# meld install
# --------------------------------------------------------------------------
    - name: Install meld
      ansible.builtin.apt:
        name: meld
        state: present
##############################################################
    - name: Install nfs-common package
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Ensure the mount directory exists
      ansible.builtin.file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Configure /etc/fstab and mount NFS share
      ansible.posix.mount:
        path: "{{ mount_point }}"
        src: "{{ nfs_server_path }}"
        fstype: nfs
        opts: "defaults,_netdev"  # _netdev はネットワーク起動後にマウントする指定
        state: mounted            # fstabに追記し、即座にマウントする
##############################################################
###################
# End of Yaml     #
###################

