---
- name: Gnome Desktop Setup for Ubuntu and debian
  hosts:
    - kvm_linux
  gather_facts: yes
  become: yes
#
  tasks:
#    - name: Include parameter from common.yaml
#      include_vars:
#        file: ./common.yaml
##############################################################
    - name: All Package update
      ansible.builtin.apt:
        update_cache: yes
        state: latest
#------------------------------------------------------------
    - name: All Package upgrade
      ansible.builtin.apt:
        upgrade: yes
        state: latest
##############################################################
    - name: Install tools
      ansible.builtin.apt:
        name:
          - ufw			# for firewall setting
          - net-tools		# for ifconfig command
          - curl		# for install any application
          - tcpdump		# for analyze tcp stream
          - auditd		# for check audit log
          - nfs-common		# for nfs mount
          - expect		# for automatic setup
          - net-tools		# for ip address check
        state: present
##############################################################
# オプション1: 最小限のUbuntuデスクトップをインストール (推奨)
    - name: Install ubuntu-desktop-minimal
      ansible.builtin.apt:
        name: ubuntu-desktop-minimal
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
      # これにはGNOMEシェル、基本的な設定、ウィンドウマネージャーなどが含まれます。
#-------------------------------------------------------------
# GDM3が既にインストールされているかを確認し、設定を再構成
    - name: Reconfigure gdm3 to ensure it's the default display manager
      ansible.builtin.shell:
        cmd: DEBIAN_FRONTEND=noninteractive dpkg-reconfigure gdm3
        # DEBIAN_FRONTEND=noninteractive を使用して対話モードを回避
      # 既にインストールされているため、変更があった場合のみ報告するように設定することも可能
      changed_when: false
      when: ansible_fqdn == "ubuntu-os.local"
##############################################################
# install gnome application
    - name: Install gnome-terminal
      ansible.builtin.apt:
        name:
          - gnome-terminal
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
#-------------------------------------------------------------
    - name: Install gedit
      ansible.builtin.apt:
        name: gedit
        state: present
##############################################################
# 1. パッケージリストの更新
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
#-------------------------------------------------------------
# 2. 日本語ロケールのインストール
    - name: Install language-pack-ja (Japanese locale)
      ansible.builtin.apt:
        name: language-pack-ja
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
#-------------------------------------------------------------
# 3. システムロケールを 'ja_JP.UTF-8' に設定
    - name: Set system locale to ja_JP.UTF-8
      community.general.locale_gen:
        name: ja_JP.UTF-8
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
#-------------------------------------------------------------
    - name: Ensure ja_JP.UTF-8 is the default system locale
      ansible.builtin.command:
        cmd: update-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
      when: ansible_fqdn == "ubuntu-os.local"        
#-------------------------------------------------------------
# 4. 日本語入力メソッド（Fcitx + Mozc）のインストール
    - name: Install Japanese Input Method (Fcitx-Mozc)
      ansible.builtin.apt:
        name:
          - fcitx
          - fcitx-mozc
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
#-------------------------------------------------------------
# 5. タイムゾーンを日本（Asia/Tokyo）に設定
    - name: Set timezone to Asia/Tokyo
      community.general.timezone:
        name: Asia/Tokyo
##############################################################
# install display agent for ubuntu
    - name: Install required VirtIO/Spice packages
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - spice-vdagent
        state: present
      when: ansible_fqdn == "ubuntu-os.local"
#-------------------------------------------------------------
    - name: Ensure qemu-guest-agent service is started and enabled (for Linux systems)
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
      when: ansible_fqdn == "ubuntu-os.local"
##############################################################
    - name: Install Desktop Icons NG for Debian
      apt:
        name: gnome-shell-extension-desktop-icons-ng
        state: present
      when: ansible_fqdn == "debian-os.local"
###################
# End of Yaml     #
###################

